# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:categories/:title
# Site settings
title: "Wouter Bulten"
description: > # this means to ignore newlines until "email:"
  A personal blog about the things I come accross daily. Ranging from machine learning and (web) development to new technologies.

email: ""
#blog logo
logo: "/assets/images/site-logo.jpg"
# blog cover
cover: "/assets/images/background_rocks_optim.jpeg"

name: 'Wouter Bulten'
author: 'Wouter Bulten'
author_image: "/assets/images/author.jpg"

paginate:	5

exclude: [vendor, node_modules, _cooking_images, _scripts] # for travis
include: [cooking]

sass:
  style: compressed
url: "https://wouterbulten.nl" # the base hostname & protocol for your site
baseurl: ""

encoding: utf-8

disqus: wouterbulten

# social icons and sharing options
social:

  - icon: linkedin
    url:  https://www.linkedin.com/in/wouterbulten
    desc: View my LinkedIn profile
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/wouterbulten
    desc:	View my profile on GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
