# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate

permalink: /:categories/:title/
# Site settings
title: "Wouter Bulten"
description: > # this means to ignore newlines until "email:"
  A personal blog about two of my passions: technology and cooking. Ranging from machine learning and development to sous vide cooking!

email: ""
#blog logo
logo: "/assets/images/site-logo.jpg"
# blog cover
cover: "/assets/images/background_rocks_optim.jpeg"

name: 'Wouter Bulten'
author: 'Wouter Bulten'
author_image: "/assets/images/author.jpg"

paginate:	8
paginate_path: "blog/:num"

exclude: [vendor, node_modules, _cooking_images, _scripts] # for travis
include: [cooking]

sass:
  style: compressed
url: "https://wouterbulten.nl" # the base hostname & protocol for your site
baseurl: ""

encoding: utf-8

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

disqus: wouterbulten

# social icons and sharing options
social:

  - icon: linkedin
    url:  https://www.linkedin.com/in/wouterbulten
    desc: View my LinkedIn profile
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/wouterbulten
    desc:	View my profile on GitHub
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
